# Stubs for tortoise (Python 3)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from tortoise.backends.base.client import BaseDBAsyncClient
from tortoise.models import Model
from typing import Any, Coroutine, Dict, List, Optional, Type

logger: Any

class Tortoise:
    apps: Dict[str, Dict[str, Type[Model]]] = ...
    @classmethod
    def get_connection(cls: Any, connection_name: str) -> BaseDBAsyncClient: ...
    @classmethod
    async def init(cls: Any, config: Optional[dict]=..., config_file: Optional[str]=..., _create_db: bool=..., db_url: Optional[str]=..., modules: Optional[Dict[str, List[str]]]=...) -> None: ...
    @classmethod
    async def close_connections(cls: Any) -> None: ...
    @classmethod
    async def generate_schemas(cls: Any, safe: Any=...) -> None: ...

def run_async(coro: Coroutine) -> None: ...
