# Stubs for tortoise.transactions (Python 3)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from tortoise.backends.base.client import BaseTransactionWrapper
from typing import Callable, Dict, Optional

current_transaction_map: Dict

def in_transaction(connection_name: Optional[str]=...) -> BaseTransactionWrapper: ...
def atomic(connection_name: Optional[str]=...) -> Callable: ...
async def start_transaction(connection_name: Optional[str]=...) -> BaseTransactionWrapper: ...
