from unittest import TestCase
from libkol.koldate import koldate


class KoldateTestCase(TestCase):
    def test_ronald_phase(self):
        self.assertEqual(koldate(52, 2, 0).ronald_phase, 0)
        self.assertEqual(koldate(52, 2, 1).ronald_phase, 1)
        self.assertEqual(koldate(52, 2, 2).ronald_phase, 2)
        self.assertEqual(koldate(52, 2, 3).ronald_phase, 3)
        self.assertEqual(koldate(52, 2, 4).ronald_phase, 4)
        self.assertEqual(koldate(52, 2, 5).ronald_phase, 5)
        self.assertEqual(koldate(52, 2, 6).ronald_phase, 6)
        self.assertEqual(koldate(52, 2, 7).ronald_phase, 7)

    def test_ronald_light(self):
        self.assertEqual(koldate(52, 2, 0).ronald_light, 0)
        self.assertEqual(koldate(52, 2, 1).ronald_light, 1)
        self.assertEqual(koldate(52, 2, 2).ronald_light, 2)
        self.assertEqual(koldate(52, 2, 3).ronald_light, 3)
        self.assertEqual(koldate(52, 2, 4).ronald_light, 4)
        self.assertEqual(koldate(52, 2, 5).ronald_light, 3)
        self.assertEqual(koldate(52, 2, 6).ronald_light, 2)
        self.assertEqual(koldate(52, 2, 7).ronald_light, 1)

    def test_grimace_phase(self):
        self.assertEqual(koldate(52, 2, 0).grimace_phase, 0)
        self.assertEqual(koldate(52, 2, 1).grimace_phase, 0)
        self.assertEqual(koldate(52, 2, 2).grimace_phase, 1)
        self.assertEqual(koldate(52, 2, 3).grimace_phase, 1)
        self.assertEqual(koldate(52, 2, 4).grimace_phase, 2)
        self.assertEqual(koldate(52, 2, 5).grimace_phase, 2)
        self.assertEqual(koldate(52, 2, 6).grimace_phase, 3)
        self.assertEqual(koldate(52, 2, 7).grimace_phase, 3)
        self.assertEqual(koldate(52, 3, 0).grimace_phase, 4)
        self.assertEqual(koldate(52, 3, 1).grimace_phase, 4)
        self.assertEqual(koldate(52, 3, 2).grimace_phase, 5)
        self.assertEqual(koldate(52, 3, 3).grimace_phase, 5)
        self.assertEqual(koldate(52, 3, 4).grimace_phase, 6)
        self.assertEqual(koldate(52, 3, 5).grimace_phase, 6)
        self.assertEqual(koldate(52, 3, 6).grimace_phase, 7)
        self.assertEqual(koldate(52, 3, 7).grimace_phase, 7)

    def test_grimace_light(self):
        self.assertEqual(koldate(52, 2, 0).grimace_light, 0)
        self.assertEqual(koldate(52, 2, 1).grimace_light, 0)
        self.assertEqual(koldate(52, 2, 2).grimace_light, 1)
        self.assertEqual(koldate(52, 2, 3).grimace_light, 1)
        self.assertEqual(koldate(52, 2, 4).grimace_light, 2)
        self.assertEqual(koldate(52, 2, 5).grimace_light, 2)
        self.assertEqual(koldate(52, 2, 6).grimace_light, 3)
        self.assertEqual(koldate(52, 2, 7).grimace_light, 3)
        self.assertEqual(koldate(52, 3, 0).grimace_light, 4)
        self.assertEqual(koldate(52, 3, 1).grimace_light, 4)
        self.assertEqual(koldate(52, 3, 2).grimace_light, 3)
        self.assertEqual(koldate(52, 3, 3).grimace_light, 3)
        self.assertEqual(koldate(52, 3, 4).grimace_light, 2)
        self.assertEqual(koldate(52, 3, 5).grimace_light, 2)
        self.assertEqual(koldate(52, 3, 6).grimace_light, 1)
        self.assertEqual(koldate(52, 3, 7).grimace_light, 1)

    def test_hamburglar_phase(self):
        self.assertEqual(koldate(52, 2, 0).hamburglar_phase, 7)
        self.assertEqual(koldate(52, 2, 1).hamburglar_phase, 9)
        self.assertEqual(koldate(52, 2, 2).hamburglar_phase, 0)
        self.assertEqual(koldate(52, 2, 3).hamburglar_phase, 2)
        self.assertEqual(koldate(52, 2, 4).hamburglar_phase, 4)
        self.assertEqual(koldate(52, 2, 5).hamburglar_phase, 6)
        self.assertEqual(koldate(52, 2, 6).hamburglar_phase, 8)
        self.assertEqual(koldate(52, 2, 7).hamburglar_phase, 10)
        self.assertEqual(koldate(52, 3, 0).hamburglar_phase, 1)
        self.assertEqual(koldate(52, 3, 1).hamburglar_phase, 3)
        self.assertEqual(koldate(52, 3, 2).hamburglar_phase, 5)

    def test_hamburglar_light(self):
        self.assertEqual(koldate(52, 2, 0).hamburglar_light, 0)
        self.assertEqual(koldate(52, 2, 1).hamburglar_light, 1)
        self.assertEqual(koldate(52, 2, 2).hamburglar_light, -1)
        self.assertEqual(koldate(52, 2, 3).hamburglar_light, 0)
        self.assertEqual(koldate(52, 2, 4).hamburglar_light, 1)
        self.assertEqual(koldate(52, 2, 5).hamburglar_light, 0)
        self.assertEqual(koldate(52, 2, 6).hamburglar_light, 1)
        self.assertEqual(koldate(52, 2, 7).hamburglar_light, 2)
        self.assertEqual(koldate(52, 3, 0).hamburglar_light, -1)
        self.assertEqual(koldate(52, 3, 1).hamburglar_light, 0)
        self.assertEqual(koldate(52, 3, 2).hamburglar_light, 0)

    def test_moonlight(self):
        self.assertEqual(koldate(52, 2, 0).moonlight, 0)
        self.assertEqual(koldate(52, 2, 1).moonlight, 2)
        self.assertEqual(koldate(52, 2, 2).moonlight, 2)
        self.assertEqual(koldate(52, 2, 3).moonlight, 4)
        self.assertEqual(koldate(52, 2, 4).moonlight, 7)
        self.assertEqual(koldate(52, 2, 5).moonlight, 5)
        self.assertEqual(koldate(52, 2, 6).moonlight, 6)
        self.assertEqual(koldate(52, 2, 7).moonlight, 6)
        self.assertEqual(koldate(52, 3, 0).moonlight, 3)
        self.assertEqual(koldate(52, 3, 1).moonlight, 5)
        self.assertEqual(koldate(52, 3, 2).moonlight, 5)
