# Stubs for tortoise.backends.sqlite.schema_generator (Python 3)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from tortoise.backends.base.schema_generator import BaseSchemaGenerator

class SqliteSchemaGenerator(BaseSchemaGenerator):
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
