# Stubs for bs4.tests.test_docs (Python 3)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

__metaclass__ = type

# Names in __all__ with no definition:
#   additional_tests
