# Stubs for tortoise.backends.base.config_generator (Python 3)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from typing import Any, Dict, List, Optional

DB_LOOKUP: Dict[str, Dict[str, Any]]

def expand_db_url(db_url: str, testing: bool=...) -> dict: ...
def generate_config(db_url: str, app_modules: Dict[str, List[str]], connection_label: Optional[str]=..., testing: bool=...) -> dict: ...
